version: '3.8'
services:
  app:
    container_name: tenantmanager
    image: tenantmanager
    build: ./
    ports:
      - "3000:8080"
    depends_on:
      - postgresqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/db_sisal
      - SPRING_DATASOURCE_USERNAME=samet
      - SPRING_DATASOURCE_PASSWORD=samet123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
  postgresqldb:
    image: postgres:latest
    container_name: postgresqldb
    environment:
      - POSTGRES_PASSWORD=samet123
      - POSTGRES_USER=samet
      - POSTGRES_DB=db_sisal