version: '0.1'
services:
  app:
    container_name: tenantmanager
    image: tenantmanager
    build: ./
    ports:
      - "3000:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres:latest
    container_name: postgresqldb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=samet123
      - POSTGRES_USER=samet
      - POSTGRES_DB=db_sisal