name: Docker TenantManager Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: './pom.xml'
      - name: Build with Maven
        run: mvn clean install --file pom.xml -DskipTests
        working-directory: ${{github.workspace}}

      - name: Set up Docker Compose
        uses: withlogicco/setup-compose-cli@v1

      - name: Build and Push Docker Images
        run: |
          docker build -t tenantmanager .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker-compose push app

      - name: Deploy to Docker Compose
        run: docker-compose up -d